### ISSUE TITLE
presence of exchange_code method insta-bricks my Rocket request handler

### ISSUE THREAD

**Issue by thomasmost** [ramosbugs/oauth2-rs#175]
I am writing a Rocket application that uses this library, and I'm running into a pretty difficult-to-parse error. The following line causes my Rocket endpoint to insta-fail with the message `thread 'rocket-worker-thread' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.',`.

```rs
let token_res = client.exchange_code(auth_code).request(http_client);
```

Here's the full endpoint implementation:

```rs
#[get("/callback?<code>&<state>")]
pub fn callback(
  code: String,
  state: String,
  mut db_connection: DBConnection,
) -> Redirect {
  dotenv().ok();
  let brex_client_id = ClientId::new(env::var("BREX_CLIENT_ID").expect("Missing BREX_CLIENT_ID"));
  let brex_client_secret =
    ClientSecret::new(env::var("BREX_CLIENT_SECRET").expect("Missing BREX_CLIENT_SECRET"));
  let auth_url = AuthUrl::new("{AUTH_URL}".to_string())
  .expect("Invalid authorization endpoint URL");

  // We can trade this authorization code for an access token
  let token_url = TokenUrl::new("{TOKEN_URL}".to_string())
  .expect("Invalid token endpoint URL");

  let auth_code = AuthorizationCode::new(code);
  let client = BasicClient::new(brex_client_id, Some(brex_client_secret), auth_url, Some(token_url));
  println!("This never gets called! But the following line is the problem...");
  let token_res = client.exchange_code(auth_code).request(http_client);
  println!("Brex returned the following token:\n{:?}\n", token_res);
  let token = match token_res {
    Ok(t) => t,
    Err(_) => return Redirect::to(format!("https://app.bend.green/oauth/error"))
  };

  let access_token = token.access_token().secret();
  let refresh_token = match token.refresh_token() {
    Some(token) => Some(token.secret()),
    None => None
  };

  let connection = &mut *db_connection;
  dal::org_service_oauth_connection::OrgServiceOauthConnection::activate(...);
  Redirect::to(format!(success_url))
}
```

and here's my Cargo.toml

```toml
[package]
name = "api-service"
version = "0.5.13"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
diesel = { git = "https://github.com/diesel-rs/diesel", features = ["mysql", "extras", "chrono"] }
dotenv = "0.15.0"
regex = "1.5.5"
rust-argon2 = "1.0"
serde = "1.0.136"
serde_derive = "1.0.136"
uuid = { version = "1.0.0", features = ["serde", "v4"] }
chrono = { version = "0.4.19", features = ["serde"] }
oauth2 = "4.2"
reqwest = { version = "0.11", default-features = false, features = ["blocking"] }

```

Thanks in advance! Any help would be appreciated
