### ISSUE TITLE
Fails to compile with `reqwest`'s http3 feature enabled.

### ISSUE THREAD

**Issue by xangelix** [ramosbugs/oauth2-rs#299]
To reproduce:

```toml
[dependencies]
openidconnect = "4.0.0"
reqwest = { version = "0.12.12", default-features = false, features = ["http3"] }
```
